export default [
  { id: 1, title: "Consider Phlebas", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 2, title: "Neuromancer", author: "William Gibson", genre: "Cyberpunk" },
  { id: 3, title: "I Have No Mouth, and I Must Scream", author: "Harlan Ellison", genre: "Science Fiction" },
  { id: 4, title: "The Player of Games", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 5, title: "Count Zero", author: "William Gibson", genre: "Cyberpunk" },
  { id: 6, title: "The City on the Edge of Forever", author: "Harlan Ellison", genre: "Science Fiction" },
  { id: 7, title: "Use of Weapons", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 8, title: "Mona Lisa Overdrive", author: "William Gibson", genre: "Cyberpunk" },
  { id: 9, title: "Dangerous Visions", author: "Harlan Ellison", genre: "Science Fiction" },
  { id: 10, title: "Excession", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 11, title: "Burning Chrome", author: "William Gibson", genre: "Cyberpunk" },
  { id: 12, title: "Repent, Harlequin! Said the Ticktockman", author: "Harlan Ellison", genre: "Science Fiction" },
  { id: 13, title: "Look to Windward", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 14, title: "Virtual Light", author: "William Gibson", genre: "Cyberpunk" },
  { id: 15, title: "Shatterday", author: "Harlan Ellison", genre: "Science Fiction" },
  { id: 16, title: "Surface Detail", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 17, title: "Idoru", author: "William Gibson", genre: "Cyberpunk" },
  { id: 18, title: "The Beast That Shouted Love at the Heart of the World", author: "Harlan Ellison", genre: "Science Fiction" },
  { id: 19, title: "Matter", author: "Iain M. Banks", genre: "Science Fiction" },
  { id: 20, title: "All Tomorrow's Parties", author: "William Gibson", genre: "Cyberpunk" },
  { id: 21, title: "A Scanner Darkly", author: "Philip K. Dick", genre: "Science Fiction" },
  { id: 22, title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", genre: "Science Fiction" },
  { id: 23, title: "Snow Crash", author: "Neal Stephenson", genre: "Cyberpunk" },
  { id: 24, title: "Cryptonomicon", author: "Neal Stephenson", genre: "Science Fiction" },
  { id: 25, title: "The Diamond Age", author: "Neal Stephenson", genre: "Cyberpunk" },
  { id: 26, title: "Foundation", author: "Isaac Asimov", genre: "Science Fiction" },
  { id: 27, title: "Foundation and Empire", author: "Isaac Asimov", genre: "Science Fiction" },
  { id: 28, title: "Second Foundation", author: "Isaac Asimov", genre: "Science Fiction" },
  { id: 29, title: "Prelude to Foundation", author: "Isaac Asimov", genre: "Science Fiction" },
  { id: 30, title: "Forward the Foundation", author: "Isaac Asimov", genre: "Science Fiction" },
  { id: 31, title: "Dune", author: "Frank Herbert", genre: "Science Fiction" },
  { id: 32, title: "Dune Messiah", author: "Frank Herbert", genre: "Science Fiction" },
  { id: 33, title: "Children of Dune", author: "Frank Herbert", genre: "Science Fiction" },
  { id: 34, title: "God Emperor of Dune", author: "Frank Herbert", genre: "Science Fiction" },
  { id: 35, title: "Heretics of Dune", author: "Frank Herbert", genre: "Science Fiction" },
  { id: 36, title: "Chapterhouse: Dune", author: "Frank Herbert", genre: "Science Fiction" },
  { id: 37, title: "Hyperion", author: "Dan Simmons", genre: "Science Fiction" },
  { id: 38, title: "The Fall of Hyperion", author: "Dan Simmons", genre: "Science Fiction" },
  { id: 39, title: "Endymion", author: "Dan Simmons", genre: "Science Fiction" },
  { id: 40, title: "The Rise of Endymion", author: "Dan Simmons", genre: "Science Fiction" },
  { id: 41, title: "Rendezvous with Rama", author: "Arthur C. Clarke", genre: "Science Fiction" },
  { id: 42, title: "2001: A Space Odyssey", author: "Arthur C. Clarke", genre: "Science Fiction" },
  { id: 43, title: "2010: Odyssey Two", author: "Arthur C. Clarke", genre: "Science Fiction" },
  { id: 44, title: "2061: Odyssey Three", author: "Arthur C. Clarke", genre: "Science Fiction" },
  { id: 45, title: "3001: The Final Odyssey", author: "Arthur C. Clarke", genre: "Science Fiction" },
  { id: 46, title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", genre: "Science Fiction" },
  { id: 47, title: "The Dispossessed", author: "Ursula K. Le Guin", genre: "Science Fiction" },
  { id: 48, title: "A Wizard of Earthsea", author: "Ursula K. Le Guin", genre: "Fantasy" },
  { id: 49, title: "The Tombs of Atuan", author: "Ursula K. Le Guin", genre: "Fantasy" },
  { id: 50, title: "The Farthest Shore", author: "Ursula K. Le Guin", genre: "Fantasy" },
  { id: 51, title: "The Lathe of Heaven", author: "Ursula K. Le Guin", genre: "Science Fiction" },
  { id: 52, title: "Slaughterhouse-Five", author: "Kurt Vonnegut", genre: "Science Fiction" },
  { id: 53, title: "Cat's Cradle", author: "Kurt Vonnegut", genre: "Science Fiction" },
  { id: 54, title: "Breakfast of Champions", author: "Kurt Vonnegut", genre: "Science Fiction" },
  { id: 55, title: "Galapagos", author: "Kurt Vonnegut", genre: "Science Fiction" },
  { id: 56, title: "The Sirens of Titan", author: "Kurt Vonnegut", genre: "Science Fiction" },
  { id: 57, title: "Fahrenheit 451", author: "Ray Bradbury", genre: "Science Fiction" },
  { id: 58, title: "The Martian Chronicles", author: "Ray Bradbury", genre: "Science Fiction" },
  { id: 59, title: "Something Wicked This Way Comes", author: "Ray Bradbury", genre: "Fantasy" },
  { id: 60, title: "Dandelion Wine", author: "Ray Bradbury", genre: "Fantasy" },
  { id: 61, title: "The Illustrated Man", author: "Ray Bradbury", genre: "Science Fiction" },
  { id: 62, title: "Brave New World", author: "Aldous Huxley", genre: "Dystopian" },
  { id: 63, title: "Island", author: "Aldous Huxley", genre: "Philosophical Fiction" },
  { id: 64, title: "1984", author: "George Orwell", genre: "Dystopian" },
  { id: 65, title: "Animal Farm", author: "George Orwell", genre: "Political Satire" },
  { id: 66, title: "We", author: "Yevgeny Zamyatin", genre: "Dystopian" },
  { id: 67, title: "The Time Machine", author: "H.G. Wells", genre: "Science Fiction" },
  { id: 68, title: "The War of the Worlds", author: "H.G. Wells", genre: "Science Fiction" },
  { id: 69, title: "The Invisible Man", author: "H.G. Wells", genre: "Science Fiction" },
  { id: 70, title: "The Island of Doctor Moreau", author: "H.G. Wells", genre: "Science Fiction" },
  { id: 71, title: "A Wrinkle in Time", author: "Madeleine L'Engle", genre: "Science Fiction" },
  { id: 72, title: "A Wind in the Door", author: "Madeleine L'Engle", genre: "Science Fiction" },
  { id: 73, title: "Many Waters", author: "Madeleine L'Engle", genre: "Science Fiction" },
  { id: 74, title: "An Acceptable Time", author: "Madeleine L'Engle", genre: "Science Fiction" },
  { id: 75, title: "The Giver", author: "Lois Lowry", genre: "Dystopian" },
  { id: 76, title: "Gathering Blue", author: "Lois Lowry", genre: "Dystopian" },
  { id: 77, title: "Messenger", author: "Lois Lowry", genre: "Dystopian" },
  { id: 78, title: "Son", author: "Lois Lowry", genre: "Dystopian" },
  { id: 79, title: "The Hunger Games", author: "Suzanne Collins", genre: "Dystopian" },
  { id: 80, title: "Catching Fire", author: "Suzanne Collins", genre: "Dystopian" },
  { id: 81, title: "Mockingjay", author: "Suzanne Collins", genre: "Dystopian" },
  { id: 82, title: "Divergent", author: "Veronica Roth", genre: "Dystopian" },
  { id: 83, title: "Insurgent", author: "Veronica Roth", genre: "Dystopian" },
  { id: 84, title: "Allegiant", author: "Veronica Roth", genre: "Dystopian" },
  { id: 85, title: "The Maze Runner", author: "James Dashner", genre: "Dystopian" },
  { id: 86, title: "The Scorch Trials", author: "James Dashner", genre: "Dystopian" },
  { id: 87, title: "The Death Cure", author: "James Dashner", genre: "Dystopian" },
  { id: 88, title: "The Kill Order", author: "James Dashner", genre: "Dystopian" },
  { id: 89, title: "Ready Player One", author: "Ernest Cline", genre: "Science Fiction" },
  { id: 90, title: "Ready Player Two", author: "Ernest Cline", genre: "Science Fiction" },
  { id: 91, title: "Artemis", author: "Andy Weir", genre: "Science Fiction" },
  { id: 92, title: "Project Hail Mary", author: "Andy Weir", genre: "Science Fiction" },
  { id: 93, title: "The Martian", author: "Andy Weir", genre: "Science Fiction" },
  { id: 94, title: "Dark Matter", author: "Blake Crouch", genre: "Science Fiction" },
  { id: 95, title: "Recursion", author: "Blake Crouch", genre: "Science Fiction" },
  { id: 96, title: "Wayward Pines", author: "Blake Crouch", genre: "Science Fiction" },
  { id: 97, title: "Pines", author: "Blake Crouch", genre: "Science Fiction" },
  { id: 98, title: "Wayward", author: "Blake Crouch", genre: "Science Fiction" },
  { id: 99, title: "The Last Town", author: "Blake Crouch", genre: "Science Fiction" },
  { id: 100, title: "The Midnight Library", author: "Matt Haig", genre: "Fantasy" },
];
