export default [
  { category: "sport", title: "Morning Run", checked: false, date: "2024-12-22" },
  { category: "job", title: "Submit Report", checked: true, date: "2024-12-23" },
  { category: "books", title: "Read Chapter 5", checked: false, date: "2024-12-24" },
  { category: "important", title: "Doctor Appointment", checked: true, date: "2024-12-25" },
  { category: "sport", title: "Yoga Class", checked: false, date: "2024-12-26" },
  { category: "job", title: "Team Meeting", checked: true, date: "2024-12-27" },
  { category: "books", title: "Finish Novel", checked: false, date: "2024-12-28" },
  { category: "important", title: "Car Maintenance", checked: false, date: "2024-12-29" },
  { category: "sport", title: "Swim Practice", checked: true, date: "2024-12-30" },
  { category: "job", title: "Code Review", checked: false, date: "2024-12-31" },
  { category: "books", title: "Buy New Book", checked: true, date: "2025-01-01" },
  { category: "important", title: "New Year Celebration", checked: true, date: "2025-01-02" },
  { category: "sport", title: "Basketball Game", checked: false, date: "2025-01-03" },
  { category: "job", title: "Update Resume", checked: false, date: "2025-01-04" },
  { category: "books", title: "Research History Topic", checked: true, date: "2025-01-05" },
  { category: "important", title: "Pay Bills", checked: false, date: "2025-01-06" },
  { category: "sport", title: "Evening Walk", checked: true, date: "2025-01-07" },
  { category: "job", title: "Prepare Presentation", checked: true, date: "2025-01-08" },
  { category: "books", title: "Library Visit", checked: false, date: "2025-01-09" },
  { category: "important", title: "Renew License", checked: false, date: "2025-01-10" },
  { category: "sport", title: "Hiking Trip", checked: true, date: "2024-12-22" },
  { category: "job", title: "Client Call", checked: false, date: "2024-12-23" },
  { category: "books", title: "Write Book Review", checked: true, date: "2024-12-24" },
  { category: "important", title: "House Cleaning", checked: false, date: "2024-12-25" },
  { category: "sport", title: "Gym Workout", checked: true, date: "2024-12-26" },
  { category: "job", title: "Plan Weekly Goals", checked: false, date: "2024-12-27" },
  { category: "books", title: "Order New Releases", checked: true, date: "2024-12-28" },
  { category: "important", title: "Call Family", checked: false, date: "2024-12-29" },
  { category: "sport", title: "Soccer Match", checked: true, date: "2024-12-30" },
  { category: "job", title: "Send Emails", checked: false, date: "2024-12-31" },
  { category: "books", title: "Organize Bookshelf", checked: true, date: "2025-01-01" },
  { category: "important", title: "Budget Planning", checked: false, date: "2025-01-02" },
  { category: "sport", title: "Cycling", checked: true, date: "2025-01-03" },
  { category: "job", title: "Attend Workshop", checked: false, date: "2025-01-04" },
  { category: "books", title: "Study for Exam", checked: true, date: "2025-01-05" },
  { category: "important", title: "Grocery Shopping", checked: false, date: "2025-01-06" },
  { category: "sport", title: "Tennis Practice", checked: true, date: "2025-01-07" },
  { category: "job", title: "Draft Proposal", checked: false, date: "2025-01-08" },
  { category: "books", title: "Donate Old Books", checked: true, date: "2025-01-09" },
  { category: "important", title: "Visit Bank", checked: false, date: "2025-01-10" },
  { category: "sport", title: "Climbing Session", checked: true, date: "2024-12-22" },
  { category: "job", title: "Fix Bugs", checked: false, date: "2024-12-23" },
  { category: "books", title: "Join Book Club", checked: true, date: "2024-12-24" },
  { category: "important", title: "Renew Subscription", checked: false, date: "2024-12-25" },
  { category: "sport", title: "Kayaking", checked: true, date: "2024-12-26" },
  { category: "job", title: "Organize Files", checked: false, date: "2024-12-27" },
  { category: "books", title: "Write Synopsis", checked: true, date: "2024-12-28" },
  { category: "important", title: "Prepare Taxes", checked: false, date: "2024-12-29" }
]