const colors = [
  { colorName: "Red", hex: "#FF0000" },
  { colorName: "Green", hex: "#00FF00" },
  { colorName: "Blue", hex: "#0000FF" },
  { colorName: "Yellow", hex: "#FFFF00" },
  { colorName: "Cyan", hex: "#00FFFF" },
  { colorName: "Magenta", hex: "#FF00FF" },
  { colorName: "Black", hex: "#000000" },
  { colorName: "Gray", hex: "#808080" },
  { colorName: "Orange", hex: "#FFA500" },
  { colorName: "Pink", hex: "#FFC0CB" },
  { colorName: "Purple", hex: "#800080" },
  { colorName: "Brown", hex: "#A52A2A" },
  { colorName: "Lime", hex: "#00FF00" },
  { colorName: "Olive", hex: "#808000" },
  { colorName: "Navy", hex: "#000080" },
  { colorName: "Teal", hex: "#008080" },
  { colorName: "Maroon", hex: "#800000" },
  { colorName: "Gold", hex: "#FFD700" },
  { colorName: "Silver", hex: "#C0C0C0" },
  { colorName: "Beige", hex: "#F5F5DC" },
  { colorName: "Ivory", hex: "#FFFFF0" },
  { colorName: "Turquoise", hex: "#40E0D0" },
  { colorName: "Lavender", hex: "#E6E6FA" },
  { colorName: "Coral", hex: "#FF7F50" },
  { colorName: "Khaki", hex: "#F0E68C" },
  { colorName: "Peach", hex: "#FFDAB9" },
  { colorName: "Mint", hex: "#98FF98" },
  { colorName: "Salmon", hex: "#FA8072" },
  { colorName: "Indigo", hex: "#4B0082" }
];

export default colors;
